"""Quick test to verify password verification fix."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from app.core.cfg_security import verify_password, hash_password

# Test 1: Valid bcrypt hash (from seed_cliente_demo.py)
bcrypt_hash = "$2b$12$D.eZtoXYYW79A0.tN9XwgOz4.t2fIqnGbiNoEY.n4Bv"
print(f"Test 1 - bcrypt hash verify '1234': {verify_password('1234', bcrypt_hash)}")
print(f"Test 1 - bcrypt hash verify 'wrong': {verify_password('wrong', bcrypt_hash)}")

# Test 2: Invalid placeholder hash (from database)
placeholder_hash = "hashed_password_40110010"
print(f"Test 2 - placeholder hash verify 'anything': {verify_password('anything', placeholder_hash)}")

# Test 3: New hash generated by our function
new_hash = hash_password("test123")
print(f"Test 3 - new hash verify 'test123': {verify_password('test123', new_hash)}")
print(f"Test 3 - new hash verify 'wrong': {verify_password('wrong', new_hash)}")

print("\nAll tests passed - no UnknownHashError thrown!")